//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSoft.Models.DBMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolMDBEntities : DbContext
    {
        public SchoolMDBEntities()
            : base("name=SchoolMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StdClass> StdClasses { get; set; }
        public virtual DbSet<StdSection> StdSections { get; set; }
        public virtual DbSet<StdPicture> StdPictures { get; set; }
        public virtual DbSet<StdGroup> StdGroups { get; set; }
        public virtual DbSet<StdProfile> StdProfiles { get; set; }
        public virtual DbSet<CustPicture> CustPictures { get; set; }
        public virtual DbSet<StdAdmission> StdAdmissions { get; set; }
        public virtual DbSet<StdTution> StdTutions { get; set; }
        public virtual DbSet<StdTType> StdTTypes { get; set; }
        public virtual DbSet<VTutuionCollectionList> VTutuionCollectionLists { get; set; }
        public virtual DbSet<TeacherEducation> TeacherEducations { get; set; }
        public virtual DbSet<TeacherPicture> TeacherPictures { get; set; }
        public virtual DbSet<TeacherPro> TeacherProes { get; set; }
    }
}
