//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSoft.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdAdmission
    {
        public int Aid { get; set; }
        public Nullable<System.DateTime> ADate { get; set; }
        public string StudentUniqueeID { get; set; }
        public string ClassName { get; set; }
        public string StdSectionName { get; set; }
        public string GroupName { get; set; }
        public Nullable<decimal> AFee { get; set; }
        public Nullable<decimal> MFee { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public string CreateBy { get; set; }
    }
}
