//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSoft.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdProfile
    {
        public int StdID { get; set; }
        public string StudentUniqueeID { get; set; }
        public string StudentName { get; set; }
        public string ClassName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string ContachNumber { get; set; }
        public string EmergencyContact { get; set; }
        public string Address { get; set; }
        public string SchoolName { get; set; }
        public string ClassRoll { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string ReferenceName { get; set; }
        public string MeritNumber { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public int SlNo { get; set; }
        public string BranchCode { get; set; }
        public string StdSectionName { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public string GroupName { get; set; }
        public string FatherOccupation { get; set; }
        public string MotherOccupation { get; set; }
        public string FatherNID { get; set; }
        public string MotherNID { get; set; }
    }
}
