//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSoft.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdTution
    {
        public int SlNo { get; set; }
        public string StudentUniqueeID { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string Pmonth { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> SysTime { get; set; }
        public string FType { get; set; }
    }
}
