//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSoft.Models.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherPro
    {
        public int Tid { get; set; }
        public string TeacherID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string Education { get; set; }
        public string Nationality { get; set; }
        public string BloodGroup { get; set; }
        public string PersentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SysTime { get; set; }
        public string CreateBy { get; set; }
    }
}
